default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: cs_skin_portfolio_development
  username: vagnercruz
  password: asdpoi04
  host: localhost

test:
  <<: *default
  database: cs_skin_portfolio_test
  username: vagnercruz
  password: asdpoi04
  host: localhost